"""Declarative rule-based routing. See `docs/routing/pipeline.md`."""

from __future__ import annotations

from magos.routing.decision import RouteDecision
from magos.routing.engine import apply_pre_transforms, route
from magos.routing.errors import (
    RouteError,
    error_envelope,
    format_dispatch_error_message,
    format_unmatched_message,
)
from magos.routing.loader import RoutingConfigError, load_config
from magos.routing.match import matches
from magos.routing.request import ENDPOINTS, Endpoint, RoutedRequest
from magos.routing.rewrites import RewriteError, apply_transforms
from magos.routing.schema import (
    AddHeader,
    AllOf,
    AnyOf,
    Compress,
    CompressMode,
    CompressOptions,
    EndpointAtom,
    GatewayMode,
    GlobMatcher,
    GuardedTransforms,
    HeaderAtom,
    HeaderPair,
    JqAtom,
    JqPatch,
    LiteralMatcher,
    Matcher,
    MatchExpr,
    ModelAtom,
    ModelFieldAtom,
    ModelFieldExpr,
    ModelFieldOp,
    NamedValue,
    Not,
    PreTransform,
    RegexMatcher,
    RemoveHeader,
    RoutingConfig,
    Rule,
    SetHeader,
    SetModel,
    Target,
    config_uses_compress,
)

__all__ = [
    "ENDPOINTS",
    "AddHeader",
    "AllOf",
    "AnyOf",
    "Compress",
    "CompressMode",
    "CompressOptions",
    "Endpoint",
    "EndpointAtom",
    "GatewayMode",
    "GlobMatcher",
    "GuardedTransforms",
    "HeaderAtom",
    "HeaderPair",
    "JqAtom",
    "JqPatch",
    "LiteralMatcher",
    "MatchExpr",
    "Matcher",
    "ModelAtom",
    "ModelFieldAtom",
    "ModelFieldExpr",
    "ModelFieldOp",
    "NamedValue",
    "Not",
    "PreTransform",
    "RegexMatcher",
    "RemoveHeader",
    "RewriteError",
    "RouteDecision",
    "RouteError",
    "RoutedRequest",
    "RoutingConfig",
    "RoutingConfigError",
    "Rule",
    "SetHeader",
    "SetModel",
    "Target",
    "apply_pre_transforms",
    "apply_transforms",
    "config_uses_compress",
    "error_envelope",
    "format_dispatch_error_message",
    "format_unmatched_message",
    "load_config",
    "matches",
    "route",
]
